# docker run -it -v $PWD:/home/apps -w /home/apps -p 5000:5000 python:3.11-slim python CharCount.py
# docker build -t charcount:v1 .
# docker run -p 5000:5000 charcount:v1

FROM python:3.11-slim
COPY $PWD /home/apps
WORKDIR /home/apps
RUN pip3 install -r requirements.txt
CMD uvicorn server:app --reload --host 0.0.0.0 --port 5000