# docker run -it -v $PWD:/home/apps -w /home/apps -p 5000:5000 python:3.9-slim python charcal.py 
# docker build -t charcal:v1 .
FROM python:3.9-slim
COPY $PWD /home/apps
WORKDIR /home/apps
CMD python charcal.py