# docker run -it -v $PWD:/home/apps -w /home/apps -p 5000:5000 python:3.10-slim python contamin1.py
# docker build -t contamin1:v1 .

FROM python:3.10-slim
COPY $PWD /home/apps/
WORKDIR /home/apps 
CMD python contamin1.py