
#docker run -it -v $PWD:/home/apps -w /home/apps -p 5000:5000 python:3.10-slim python multab.py
#docker build -t multab:v1 .


#kubectl create deployment multab --image=multab:v1
#kubectl logs 
#kubectl delete deploymnets multab

FROM python:3.10-slim
COPY $PWD /home/apps
WORKDIR /home/apps
CMD python multab.py