# docker build -t pangram:v1 .
# docker run -it -v $PWD:/home/apps -w /home/apps -p 5000:5000 python:3.10-slim python pangram.py

FROM python:3.10-slim
COPY $PWD /home/apps
WORKDIR /home/apps
CMD python pangram.py