# To run logic only
# docker run -it -v $pwd:/home/apps -w /home/apps python:3.11-slim python stringscramble.py


# To run as server
# docker build -t scramble:v1 .
# docker run -p 5000:5000 scramble:v1


FROM python:3.11-slim
COPY $PWD /home/apps
WORKDIR /home/apps
RUN pip3 install -r requirements.txt
CMD uvicorn "server:app" --reload --host 0.0.0.0 --port 5000