# docker run -it -p 5000:5000 -w \home\apps -v $PWD:\home\apps server.py
#---
# docker build -t roman:v1 .
# docker run -p 5000:5000 roman:v1

FROM python:3.11-slim
COPY . /home/apps
WORKDIR /home/apps
RUN pip3 install -r requirements.txt
CMD ["gunicorn","-w","1","-b","0.0.0.0:5000","server:app"]