# docker run -it -v $PWD:/home/apps -w /home/apps -p 5000:5000 python:3.9-slim python sqrt.py
#docker build -t sqrt:v1 .



FROM python:3.10-slim
COPY $PWD /home/apps
WORKDIR /home/apps
CMD python sqrt.py