#docker build -t cypher:v1 .
# docker run -p 5000:5000 cypher:v1

FROM python:3.11-slim
COPY $PWD /home/apps
WORKDIR /home/apps
RUN pip3 install -r requirements.txt
CMD python CypherProject/manage.py runserver 0.0.0.0:5000