#docker run -it -v $PWD:/home/apps -w /home/apps -p 5000:5000 python:3.11-slim #python ccardencrypt.py

#docker build -t ccardencrypt:v1 .

#kubectl create deployment ccardencrypt --image=ccardencrypt:v1
#kubectl get pods
#kubectl logs <cont>
#kubectl delete deployment ccardencrypt


FROM python:3.11-slim
COPY $PWD /home/apps
WORKDIR /home/apps
CMD python ccardencrypt.py
