# docker run -it -v $PWD:/home/apps -w /home/apps -p 5000:5000 python:3.11-slim python latestdate.py
# docker build -t latestdate:v1 .
# docker run -p 5000:5000 <id>

FROM python:3.11-slim
COPY $PWD /home/apps
WORKDIR /home/apps
RUN pip3 install -r requirements.txt
CMD python server.py