# docker run -it -v $PWD:/home/apps -w /home/apps -p 5000:5000 python:3.11-slim python factor.py
# docker build -t server:v1 .
##kubectl create deployment server --image=server:v1
# kubectl expose deployment server --port=5000
# kubectl port-forward svc/server 5000:5000 &






FROM python:3.11-slim
COPY $PWD /home/apps
WORKDIR /home/apps
RUN pip3 install -r requirements.txt
CMD python server.py