# docker run -it -p 5000:5000 -v $PWD:/home/apps -w /home/apps python:3.11-slim python reducefraction.py
# docker build -t server:v1 .


FROM python:3.11-slim
COPY $PWD /home/apps
WORKDIR /home/apps
RUN pip3 install -r requirements.txt
CMD python server.py