#docker run -it -v $PWD:/home/apps -w /home/apps -p 5000:5000 python:3.10-slim python vowelone.py
#docker build -t vowelone:v1 .

# docker build -t vowelone:v1 .
# kubectl create deployment vowelone --image vowelone:v1
# kubectl delete deployment vowelone

FROM python:3.10-slim
COPY $PWD /home/apps
WORKDIR /home/apps
CMD python vowelone.py
