# docker run -it -v $PWD:/home/apps -w /home/apps -p 5000:5000 python:3.11-slim python perstr.py
# docker build -t perstrng:v1 .
# kubectl create deployment perstr --image=perstrng:v1


FROM python:3.11-slim
COPY $PWD /home/apps
WORKDIR /home/apps
CMD python perstr.py
