# docker run -it -v $PWD:/home/apps -w /home/apps -p 5000:5000 python:3.11-slim python matrixadd.py
# docker build -t matrixadd:v1 .

FROM python:3.11-slim
COPY $PWD /home/apps
WORKDIR /home/apps
RUN pip3 install -r requirements.txt
# EXPOSE 5000
CMD python server.py
