# docker run -it -v $PWD:/home/apps -w /home/apps/python -p 5000:5000 python:3.11-slim python intseq.py
# docker build -t intseq:v1 .

FROM python:3.11-slim
COPY $PWD /home/apps
WORKDIR /home/apps
CMD python server.py