# docker run -it -v $PWD:/home/apps -w /home/apps -p 5000:5000 python:3.11-slim python rocks.py
# docker build -t rocks:v1 .


FROM python:3.11-slim
COPY $PWD /home/apps 
WORKDIR /home/apps 
CMD python rocks.py