#docker build -t rev:v1 .
#docker run -d -p 5000:5000 rev:v1


FROM python:3.11-slim
COPY . /home/apps
WORKDIR /home/apps
RUN pip3 install -r requirements.txt
CMD uvicorn --reload --host 0.0.0.0 --port 5000 server:app