# docker run -it -v $PWD:/home/apps -w /home/apps -p 5000:5000 python:3.10-slim python smallhighpow.py
# docker build -t smallhighpow:v1 .

FROM python:3.10-slim
COPY $PWD /home/apps
WORKDIR /home/apps 
CMD python smallhighpow.py