# docker run -it -v $PWD:/home/apps -w /home/apps -p 5000:5000 python:3.11-slim python twodtoarray.py

# docker build -t twodtoarray:v1 .

# kubectl create deployment twodtoarray --image=twodtoarray:v1 
# kubectl get pods
# kubectl logs <c -id>
# kubectl delete deployment twodtoarray
FROM python:3.11-slim
COPY $PWD /home/apps
WORKDIR /home/apps 
CMD python twodtoarray.py