#docker run -it -v $PWD \home\apps -w \home\apps -p 5000:5000 python:3.11-slim server:app
# docker build -t bs:v1 .
# docker run -p 5000:5000 bs:v1

FROM python:3.11-slim
COPY . /tmp/bs
WORKDIR /tmp/bs/
RUN pip3 install -r requirements.txt
#CMD ['gunicorn','-w','1','-b','0.0.0.0:5000','/tmp/bs/server:app']
CMD ["gunicorn","-w","1","-b","0.0.0.0:5000","server:app"]