# docker run -it -v $PWD:/home/apps -w /home/apps/ -p 5000:5000 python:3.9-slim python nicearray.py
# docker build -t nicearray:v1 .

FROM python:3.9-slim
COPY $PWD /home/apps/
WORKDIR /home/apps
CMD python nicearray.py