# docker run -it -w /home/apps -v $PWD:/home/apps -p 5000:5000 python:3.11-slim python subset.py
#docker build -t subset:v1 .

#kubectl create deployment subset --image:subset:v1
#kubectl get pods
# kubectl logs <id>
# kubectl delete deployment subset

FROM python:3.11-slim
COPY $PWD /home/apps
WORKDIR /home/apps 
CMD python subset.py