# docker run -it -w /home/apps -v $PWD:/home/apps -p 5000:5000 python:3.11-slim python server.py
#docker build -t subset:v1 .

#kubectl create deployment subset --image=subset:v1
# kubectl expose deployment subset --port=5000
#kubectl get pods
# kubectl logs <id>
# kubectl delete deployment subset

FROM python:3.11-slim
COPY $PWD /home/apps
WORKDIR /home/apps
RUN pip3 install -r requirements.txt
CMD python server.py