# docker build -t zigzag:v1 .
# docker run -d -p 5000:5000 zigzag:v1

FROM python:3.11-slim
COPY $PWD /home/apps
WORKDIR /home/apps
RUN pip3 install -r requirements.txt
CMD gunicorn -w 1 -b 0.0.0.0:5000 server:app