# docker run -it -v $PWD:/home/apps -w /home/apps -p 5000:5000 python:3.11-slim python3 AddNosLL.py
# docker build -t addnos:v1 .
#docker run -p 5000:5000 -d addnos:v1

FROM python:3.11-slim
COPY $PWD /home/apps
WORKDIR /home/apps
RUN pip3 install -r requirements.txt
CMD gunicorn -b 0.0.0.0:5000 -w 1 server:app
