# docker run -it -v $PWD:/home/apps -w /home/apps -p 5000:5000 python:3.11-slim python trainsum.py
# docker build -t trainsum:v1 .
# kubectl create deployment trainsum --image=trainsum:v1
# kubectl get pods
# kubectl logs <id>
# kubectl delete deployment 


FROM python:3.11-slim
COPY $PWD /home/apps
WORKDIR /home/apps
CMD python trainsum.py