FROM python:3.9-slim
COPY $PWD /home/apps
WORKDIR /home/apps
CMD python coffee.py


# docker run -it -v $PWD:/home/apps -w /home/apps -p 5000:5000 python:3.10-slim python coffee.py
# docker build -t coffee:v1 .