# docker run -it -v $PWD:/home/apps -p 5000:5000 -w /home/apps python:3.11-slim python smslottery.py
# docker build -t smslottery:v1 .


# kubectl create deployment smslottery --image=smslottery:v1
# kubectl get pods


FROM python:3.11-slim
COPY $PWD /home/apps
WORKDIR /home/apps
CMD python smslottery.py