# docker run -it -v $PWD:/home/apps -w /home/apps -p 5000:5000 python:3.10-slim python revadd.py

# docker build -t revadd:v1 . 

#kubectl create deployment revadd --image=revadd:v1

FROM python:3.10-slim
COPY $PWD /home/apps/
WORKDIR /home/apps
CMD python revadd.py
