apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: html
  name: html
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: html
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
