# docker build -t html:v1 .
# kubectl create deployment html --image=html:v1
# kubectl expose deployment html --port=80
#kubectl get services
#kubectl port-forward svc/html 8080:80

FROM nginx
COPY $PWD /usr/share/nginx/html