# docker run -it -v $PWD:/home/apps -w /home/apps -p 5000:5000 python:3.11-slim python consecnos.py
# docker build -t consec:v1 .
# kubectl create deployment consec --image=consec:v1
# kubectl logs 
# kubectl delete deployment consec:v1
# docker images
# docker rmi <>

FROM python:3.11-slim
COPY $PWD /home/apps
WORKDIR /home/apps
CMD python consecnos.py