#docker run -it -p 5000:5000 -v .:/home/apps -w /home/apps python:3.11-slim python3 stair.py
# docker build -t app:v1 .


FROM python:3.11-slim
COPY . /home/apps
WORKDIR /home/apps
RUN pip3 install -r requirements.txt

CMD ["gunicorn","-w","1","-b","0.0.0.0:5000","server:app"]
# CMD python3 