# docker run -it -v $PWD:/home/apps -w /home/apps -p 5000:4321 python:3.11-slim python jungerstein1.py

#----
## docker run -it -v $PWD:/home/apps -w /home/apps -p 5000:4321 python:3.11-slim bash
## pip install -r requirments.txt
## python server.py
#------------


# docker build -t junger:v1 . 
# docker-compose up

# kubectl create deployment junger --image=junger:v1
# kubectl get pods
# kubectl logs <>
# kubectl delete deployment <> 

FROM python:3.11-slim
COPY . /home/apps
WORKDIR /home/apps
RUN pip install -r requirements.txt
# CMD python jungerstein1.py
CMD python server.py