# docker run -it -w $PWD -v $PWD:/home/apps -p 5000:5000 python:3.11-slim python urinal.py

# docker build -t urinal:v1 .
# kubectl create deployment urinal --image=urinal:v1 

FROM python:3.11-slim
COPY $PWD /home/apps
WORKDIR /home/apps 
RUN pip install -r /home/apps/requirments.txt
CMD python server.py
