# docker run -it -v $PWD:/home/apps -w /home/apps -p 5000:5000 python:3.11-slim python paranthesis.py

# docker build -t paranthesis:v1 .

# kubectl create deployment --image= paranthesis:v1
# kubectl get pods
# kubectl logs 
# kubectl delete deployment paranthesis:v1


FROM python:3.11-slim
COPY $PWD:/home/apps
WORKDIR /home/apps
CMD python paranthesis.py