# docker run -it -v $PWD:/home/apps -w /home/apps -p 5000:5000 python:3.11-slim python indexcap.py
# docker build -t indexcap:v1 .
# kubectl create deployment indexcap --image=indexcap:v1

 

FROM python:3.11-slim
COPY $PWD /home/apps
WORKDIR /home/apps
CMD python indexcap.py