# docker run -it -v $PWD:/home/apps -w /home/apps -p 5000:5000 -n rmsmll python:3.10-slim python rmsmll.py

#docker build -t rmsmll:v1 .

#kubectl create deployment -image=rmsmll
# kubectl get deployments
# kubectl delete deployment
#docker ps -a
# 

FROM python:3.10-slim
COPY $PWD /home/apps
WORKDIR /home/apps
CMD python rmsmll.py