# docker run -it -v $PWD:/home/apps -w /home/apps -p 5000:5000 python:3.10-slim python hashtaggen.py

#docker build -t hashtaggen:v1 .
# kubectl create deployment hashtaggen --image=hashtaggen:v1
# kubectl logs pod_name


FROM python:3.10-slim
COPY $PWD /home/apps
WORKDIR /home/apps 
CMD python hashtaggen.py
