# docker run -it -v $PWD:/home/apps -w /home/apps -p 5000:5000 python:3.11-slim python addtest.py


# docker build -t addtest:v1 .
# docker run -d -p 5000:5000 addtest:v1
# docker exec -it <c id> bash
# kill 7



FROM python:3.11-slim
COPY $PWD /home/apps
WORKDIR /home/apps
EXPOSE 5000
RUN pip install -r requirements.txt
CMD python server.py
