# docker run -it -v $PWD:/home/apps -w /home/apps python:3.11-slim python Share.py

#docker build -t share:v1 .
# docker run -d -p 5000:5000 share:v1 


FROM python:3.11-slim
COPY $PWD /home/apps
WORKDIR /home/apps
RUN pip3 install -r requirements.txt
CMD python server.py