# docker run -it -v $PWD:/home/apps -w /home/apps -p 5000:5000 python:3.10-slim python ascii.py
# docker build -t ascii:v1 .

# kubectl create deployment ascii --image:ascii:v1
# kubectl get pods 
# kubectl logs <pod>
#kubectl delete deployment ascii 

FROM python:3.10-slim
COPY $PWD /home/apps
WORKDIR /home/apps
CMD python ascii.py