version: "3"
services:
  # app:
  #   build: .
  #   ports: 
  #     - 5000:5000
  #   volumes:
  #     - $PWD:/home/apps
  
  web:
  # http://localhost:8080/
    image: nginx
    volumes:
       - ./templates:/usr/share/nginx/html
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80  