# docker run -it -v $PWD:/home/apps -p 5000:5000 -w /home/apps python:3.11-slim python diffbwcoll.py
# docker build -t diffbwcoll:v1 .
# docker run -p 5000:5000 diffbwcoll:v1


FROM python:3.11-slim
COPY $PWD /home/apps
WORKDIR /home/apps
RUN pip3 install -r requirements.txt
CMD uvicorn --reload --host 0.0.0.0 --port 5000 server:app
